#!/bin/sh
mkdir /home/dotcloud/code/logs
chmod 777 /home/dotcloud/code/logs

#crontab /home/dotcloud/code/config/_postinstall_crontab_file

#/opt/ve/2.6/bin/python /home/dotcloud/code/setupAndBaseFunctions/setupApp.py /home/dotcloud/code/config/twitterCrowded.cfg dotcloud