#!/bin/sh
/opt/ve/2.6/bin/python /home/dotcloud/code/setupAndBaseFunctions/setupApp.py /home/dotcloud/code/config/twitterCrowded.cfg dotcloud >> /home/dotcloud/code/errorOutput/setupAppErrors.log 2>&1

crontab /home/dotcloud/code/config/_postinstall_crontab_file

